[2022-08-02 09:00:34,094] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T09:00:15.886220+00:00 [queued]>
[2022-08-02 09:00:34,107] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T09:00:15.886220+00:00 [queued]>
[2022-08-02 09:00:34,107] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 09:00:34,108] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-02 09:00:34,108] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 09:00:34,129] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): records_saving> on 2022-08-02 09:00:15.886220+00:00
[2022-08-02 09:00:34,134] {standard_task_runner.py:52} INFO - Started process 1623 to run task
[2022-08-02 09:00:34,138] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'records_saving', 'manual__2022-08-02T09:00:15.886220+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpl7k8iuiu', '--error-file', '/tmp/tmp1zwa8lm6']
[2022-08-02 09:00:34,138] {standard_task_runner.py:80} INFO - Job 171: Subtask records_saving
[2022-08-02 09:00:34,222] {task_command.py:371} INFO - Running <TaskInstance: Demo.records_saving manual__2022-08-02T09:00:15.886220+00:00 [running]> on host 31353b71d6cb
[2022-08-02 09:00:34,330] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=records_saving
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T09:00:15.886220+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-02T09:00:15.886220+00:00
[2022-08-02 09:00:34,352] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 09:00:34,356] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS public."Files"
(
    id integer NOT NULL,
    name character(80)[] COLLATE pg_catalog."default" NOT NULL,
    size bigint,
    CONSTRAINT "Files_pkey" PRIMARY KEY (id)
), parameters: None
[2022-08-02 09:00:34,358] {postgres.py:94} INFO - NOTICE:  relation "Files" already exists, skipping

[2022-08-02 09:00:34,377] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Demo, task_id=records_saving, execution_date=20220802T090015, start_date=20220802T090034, end_date=20220802T090034
[2022-08-02 09:00:34,430] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-02 09:00:34,493] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
