[2022-07-27 16:33:20,828] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.container_creation manual__2022-07-27T16:32:52.259694+00:00 [queued]>
[2022-07-27 16:33:20,839] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.container_creation manual__2022-07-27T16:32:52.259694+00:00 [queued]>
[2022-07-27 16:33:20,840] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 16:33:20,840] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-27 16:33:20,841] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 16:33:21,148] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): container_creation> on 2022-07-27 16:32:52.259694+00:00
[2022-07-27 16:33:21,168] {standard_task_runner.py:52} INFO - Started process 722 to run task
[2022-07-27 16:33:21,191] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'container_creation', 'manual__2022-07-27T16:32:52.259694+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp0blx5isz', '--error-file', '/tmp/tmpro17xto6']
[2022-07-27 16:33:21,193] {standard_task_runner.py:80} INFO - Job 14: Subtask container_creation
[2022-07-27 16:33:21,525] {task_command.py:371} INFO - Running <TaskInstance: Demo.container_creation manual__2022-07-27T16:32:52.259694+00:00 [running]> on host 3aa4098107fa
[2022-07-27 16:33:21,866] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=container_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-07-27T16:32:52.259694+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-27T16:32:52.259694+00:00
[2022-07-27 16:33:21,888] {base.py:68} INFO - Using connection ID 'sftp_demo' for task execution.
[2022-07-27 16:33:22,063] {base.py:68} INFO - Using connection ID 'sftp_demo' for task execution.
[2022-07-27 16:33:22,064] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 18, in create_container
    test.list_directory()
TypeError: list_directory() missing 1 required positional argument: 'path'
[2022-07-27 16:33:22,081] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Demo, task_id=container_creation, execution_date=20220727T163252, start_date=20220727T163320, end_date=20220727T163322
[2022-07-27 16:33:22,273] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task container_creation (list_directory() missing 1 required positional argument: 'path'; 722)
[2022-07-27 16:33:22,289] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-27 16:33:22,388] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
